services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:api
    ports:
      - '3000:3000'
    env_file:
      - ./apps/api-gateway/.env
    depends_on:
      - rabbitmq
      - postgres

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:orders
    env_file:
      - ./apps/order-service/.env
    depends_on:
      - rabbitmq
      - postgres

  products-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:products
    env_file:
      - ./apps/products-service/.env
    depends_on:
      - rabbitmq
      - postgres

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:payment
    env_file:
      - ./apps/payment-service/.env
    depends_on:
      - rabbitmq
      - postgres

volumes:
  postgres_data:
