export const MICROSERVICE_CLIENTS = {
  USERS_SERVICE: 'USERS_SERVICE',
  ORDERS_SERVICE: 'ORDERS_SERVICE',
  PAYMENTS_SERVICE: 'PAYMENTS_SERVICE',
  PRODUCTS_SERVICE: 'PRODUCTS_SERVICE',
} as const;
